// 타로 카드 해석 데이터 (Major Arcana 22장)
// tarotap 패키지와 함께 사용

export interface TarotMeaning {
  id: string
  name: string
  nameEn: string
  number: number
  keywords: string[]
  upright: string
  reversed: string
  description: string
  element?: string
  zodiac?: string
}

export const majorArcanaMeanings: TarotMeaning[] = [
  {
    id: 'the-fool',
    name: '바보',
    nameEn: 'The Fool',
    number: 0,
    keywords: ['새로운 시작', '모험', '순수함', '자유'],
    upright: '새로운 시작, 순수한 마음으로 도전하세요. 두려움 없이 앞으로 나아갈 때입니다. 미지의 세계가 당신을 기다리고 있습니다.',
    reversed: '무모한 행동을 조심하세요. 충분한 준비 없이 뛰어드는 것은 위험할 수 있습니다. 신중함이 필요한 시기입니다.',
    description: '절벽 끝에 서 있는 젊은이. 새로운 여정의 시작을 상징합니다.',
    element: '공기',
  },
  {
    id: 'the-magician',
    name: '마법사',
    nameEn: 'The Magician',
    number: 1,
    keywords: ['의지력', '창조력', '자원', '능력'],
    upright: '당신에게는 목표를 이룰 모든 도구가 있습니다. 자신의 능력을 믿고 행동으로 옮기세요. 창조적 에너지가 넘칩니다.',
    reversed: '재능을 낭비하고 있을 수 있습니다. 집중력 부족이나 의지 박약을 경계하세요. 조작이나 속임수에 주의하세요.',
    description: '하늘과 땅을 연결하는 마법사. 의지와 행동의 힘을 상징합니다.',
    element: '공기',
    zodiac: '수성',
  },
  {
    id: 'the-high-priestess',
    name: '여교황',
    nameEn: 'The High Priestess',
    number: 2,
    keywords: ['직관', '신비', '내면의 지혜', '잠재의식'],
    upright: '내면의 목소리에 귀 기울이세요. 직관이 답을 알고 있습니다. 표면 아래 숨겨진 진실을 찾을 때입니다.',
    reversed: '직관을 무시하고 있거나, 비밀이 드러날 수 있습니다. 내면의 목소리를 억압하지 마세요.',
    description: '달과 베일 사이에 앉은 여사제. 숨겨진 지식과 직관을 상징합니다.',
    element: '물',
    zodiac: '달',
  },
  {
    id: 'the-empress',
    name: '여황제',
    nameEn: 'The Empress',
    number: 3,
    keywords: ['풍요', '모성', '자연', '창조'],
    upright: '풍요와 번영의 시기입니다. 창조적 에너지가 결실을 맺습니다. 자신과 타인을 돌보는 것이 중요합니다.',
    reversed: '창조적 막힘이나 의존성 문제가 있을 수 있습니다. 자기 돌봄에 소홀하지 마세요.',
    description: '자연 속의 여황제. 대지의 풍요와 모성을 상징합니다.',
    element: '땅',
    zodiac: '금성',
  },
  {
    id: 'the-emperor',
    name: '황제',
    nameEn: 'The Emperor',
    number: 4,
    keywords: ['권위', '구조', '통제', '아버지'],
    upright: '질서와 안정을 세울 때입니다. 리더십을 발휘하고 책임을 지세요. 규율과 구조가 성공을 가져옵니다.',
    reversed: '지나친 통제욕이나 권위주의에 주의하세요. 유연성이 필요합니다. 아버지 또는 권위자와의 갈등이 있을 수 있습니다.',
    description: '왕좌에 앉은 황제. 권위와 안정을 상징합니다.',
    element: '불',
    zodiac: '양자리',
  },
  {
    id: 'the-hierophant',
    name: '교황',
    nameEn: 'The Hierophant',
    number: 5,
    keywords: ['전통', '가르침', '신앙', '제도'],
    upright: '전통적 가치나 가르침에서 지혜를 찾으세요. 멘토나 스승의 조언이 도움이 됩니다. 영적 성장의 시기입니다.',
    reversed: '관습에 도전하거나 자신만의 길을 찾을 때입니다. 독단적 사고방식을 경계하세요.',
    description: '두 제자 앞의 교황. 영적 가르침과 전통을 상징합니다.',
    element: '땅',
    zodiac: '황소자리',
  },
  {
    id: 'the-lovers',
    name: '연인',
    nameEn: 'The Lovers',
    number: 6,
    keywords: ['사랑', '선택', '조화', '관계'],
    upright: '중요한 선택의 순간입니다. 사랑과 조화가 찾아옵니다. 가치관에 따른 결정을 내리세요.',
    reversed: '관계의 불화나 잘못된 선택에 주의하세요. 내면의 갈등이 있을 수 있습니다.',
    description: '천사 아래의 남녀. 사랑과 선택을 상징합니다.',
    element: '공기',
    zodiac: '쌍둥이자리',
  },
  {
    id: 'the-chariot',
    name: '전차',
    nameEn: 'The Chariot',
    number: 7,
    keywords: ['승리', '의지력', '결단', '전진'],
    upright: '강한 의지로 승리를 거머쥘 수 있습니다. 장애물을 극복하고 전진하세요. 목표를 향해 나아갈 때입니다.',
    reversed: '방향을 잃거나 통제력을 상실할 수 있습니다. 공격성을 조절하세요.',
    description: '전차를 모는 전사. 승리와 의지력을 상징합니다.',
    element: '물',
    zodiac: '게자리',
  },
  {
    id: 'strength',
    name: '힘',
    nameEn: 'Strength',
    number: 8,
    keywords: ['용기', '인내', '내면의 힘', '자기 통제'],
    upright: '내면의 힘으로 어려움을 극복하세요. 부드러움 속에 진정한 강인함이 있습니다. 인내심을 가지세요.',
    reversed: '자기 의심이나 내면의 약함에 직면할 수 있습니다. 두려움을 극복할 용기를 찾으세요.',
    description: '사자를 다루는 여인. 내면의 힘과 용기를 상징합니다.',
    element: '불',
    zodiac: '사자자리',
  },
  {
    id: 'the-hermit',
    name: '은둔자',
    nameEn: 'The Hermit',
    number: 9,
    keywords: ['성찰', '고독', '내면 탐구', '지혜'],
    upright: '홀로 있는 시간이 필요합니다. 내면을 탐구하고 진정한 자신을 찾으세요. 명상과 성찰의 시기입니다.',
    reversed: '고립이 지나치거나 내면 탐구를 회피하고 있을 수 있습니다. 균형을 찾으세요.',
    description: '등불을 든 현자. 내면의 빛과 지혜를 상징합니다.',
    element: '땅',
    zodiac: '처녀자리',
  },
  {
    id: 'wheel-of-fortune',
    name: '운명의 수레바퀴',
    nameEn: 'Wheel of Fortune',
    number: 10,
    keywords: ['운명', '변화', '순환', '행운'],
    upright: '운명의 바퀴가 돌아갑니다. 좋은 변화가 찾아올 수 있습니다. 기회를 잡으세요.',
    reversed: '예상치 못한 장애물이나 불운에 직면할 수 있습니다. 이 또한 지나갈 것입니다.',
    description: '돌아가는 운명의 바퀴. 삶의 순환과 변화를 상징합니다.',
    element: '불',
    zodiac: '목성',
  },
  {
    id: 'justice',
    name: '정의',
    nameEn: 'Justice',
    number: 11,
    keywords: ['공정', '진실', '균형', '책임'],
    upright: '공정한 결과가 기다립니다. 진실이 드러나고 정의가 실현됩니다. 책임감 있는 결정을 내리세요.',
    reversed: '불공정함이나 거짓에 주의하세요. 자신의 행동에 대한 책임을 회피하지 마세요.',
    description: '저울과 검을 든 정의의 여신. 균형과 공정을 상징합니다.',
    element: '공기',
    zodiac: '천칭자리',
  },
  {
    id: 'the-hanged-man',
    name: '매달린 사람',
    nameEn: 'The Hanged Man',
    number: 12,
    keywords: ['희생', '새로운 관점', '일시정지', '내려놓음'],
    upright: '다른 관점에서 상황을 바라보세요. 때로는 멈춤이 필요합니다. 포기가 아닌 지혜로운 기다림입니다.',
    reversed: '불필요한 희생을 하고 있거나 변화를 거부하고 있을 수 있습니다.',
    description: '거꾸로 매달린 사람. 새로운 시각과 희생을 상징합니다.',
    element: '물',
    zodiac: '해왕성',
  },
  {
    id: 'death',
    name: '죽음',
    nameEn: 'Death',
    number: 13,
    keywords: ['끝', '변화', '전환', '재탄생'],
    upright: '한 장이 끝나고 새로운 장이 시작됩니다. 변화를 두려워하지 마세요. 끝은 곧 새로운 시작입니다.',
    reversed: '변화에 저항하거나 과거에 집착하고 있을 수 있습니다. 내려놓을 것을 내려놓으세요.',
    description: '말 위의 해골 기사. 변화와 전환을 상징합니다.',
    element: '물',
    zodiac: '전갈자리',
  },
  {
    id: 'temperance',
    name: '절제',
    nameEn: 'Temperance',
    number: 14,
    keywords: ['균형', '조화', '인내', '절제'],
    upright: '균형과 조화를 추구하세요. 극단을 피하고 중용의 길을 걸으세요. 인내심이 좋은 결과를 가져옵니다.',
    reversed: '불균형이나 과잉에 주의하세요. 극단적인 행동을 자제하세요.',
    description: '물을 섞는 천사. 조화와 균형을 상징합니다.',
    element: '불',
    zodiac: '사수자리',
  },
  {
    id: 'the-devil',
    name: '악마',
    nameEn: 'The Devil',
    number: 15,
    keywords: ['속박', '유혹', '그림자', '집착'],
    upright: '무엇에 얽매여 있는지 인식하세요. 물질적 욕망이나 중독에 주의하세요. 진정한 자유를 찾으세요.',
    reversed: '속박에서 벗어나기 시작합니다. 자기 파괴적 패턴을 극복할 수 있습니다.',
    description: '사슬에 묶인 두 사람과 악마. 속박과 유혹을 상징합니다.',
    element: '땅',
    zodiac: '염소자리',
  },
  {
    id: 'the-tower',
    name: '탑',
    nameEn: 'The Tower',
    number: 16,
    keywords: ['급변', '파괴', '깨달음', '해방'],
    upright: '예상치 못한 변화가 찾아옵니다. 낡은 것이 무너지고 새로운 것이 세워집니다. 충격 속에서 진실을 발견합니다.',
    reversed: '변화를 피하려 하지만 결국 직면하게 됩니다. 더 큰 재앙을 막기 위해 작은 변화를 받아들이세요.',
    description: '번개 맞은 탑. 급격한 변화와 깨달음을 상징합니다.',
    element: '불',
    zodiac: '화성',
  },
  {
    id: 'the-star',
    name: '별',
    nameEn: 'The Star',
    number: 17,
    keywords: ['희망', '치유', '영감', '평화'],
    upright: '폭풍이 지나고 별이 뜹니다. 희망과 치유의 시기입니다. 미래에 대한 믿음을 가지세요.',
    reversed: '절망감이나 희망 상실에 주의하세요. 작은 빛이라도 찾아보세요.',
    description: '별 아래 물을 붓는 여인. 희망과 영감을 상징합니다.',
    element: '공기',
    zodiac: '물병자리',
  },
  {
    id: 'the-moon',
    name: '달',
    nameEn: 'The Moon',
    number: 18,
    keywords: ['환상', '직관', '불안', '무의식'],
    upright: '모든 것이 명확하지 않습니다. 직관을 믿되 환상에 속지 마세요. 두려움과 마주할 용기를 가지세요.',
    reversed: '혼란이 걷히고 진실이 드러납니다. 불안과 두려움을 극복할 수 있습니다.',
    description: '달 아래의 개와 늑대. 환상과 무의식을 상징합니다.',
    element: '물',
    zodiac: '물고기자리',
  },
  {
    id: 'the-sun',
    name: '태양',
    nameEn: 'The Sun',
    number: 19,
    keywords: ['기쁨', '성공', '활력', '명확함'],
    upright: '밝은 미래가 기다립니다. 성공과 기쁨의 시기입니다. 긍정적 에너지가 넘칩니다.',
    reversed: '일시적인 실패나 낙관주의의 과잉에 주의하세요. 그래도 밝은 날은 옵니다.',
    description: '태양 아래의 아이. 기쁨과 생명력을 상징합니다.',
    element: '불',
    zodiac: '태양',
  },
  {
    id: 'judgement',
    name: '심판',
    nameEn: 'Judgement',
    number: 20,
    keywords: ['부활', '판단', '소명', '재평가'],
    upright: '과거를 돌아보고 교훈을 얻으세요. 새로운 부름에 응답할 때입니다. 내면의 목소리를 따르세요.',
    reversed: '자기 비판이 너무 가혹하거나 과거에서 벗어나지 못하고 있습니다.',
    description: '나팔 소리에 일어나는 사람들. 부활과 각성을 상징합니다.',
    element: '불',
    zodiac: '명왕성',
  },
  {
    id: 'the-world',
    name: '세계',
    nameEn: 'The World',
    number: 21,
    keywords: ['완성', '성취', '통합', '여행'],
    upright: '한 주기가 완성됩니다. 목표를 달성하고 새로운 단계로 나아갑니다. 세상이 당신 앞에 열려 있습니다.',
    reversed: '완성이 지연되거나 마무리가 필요합니다. 조금만 더 노력하세요.',
    description: '월계관 안에서 춤추는 인물. 완성과 성취를 상징합니다.',
    element: '땅',
    zodiac: '토성',
  },
]

// Minor Arcana - 완드 (Wands) - 불의 원소
export const wandsMeanings: TarotMeaning[] = [
  {
    id: 'ace-of-wands',
    name: '완드 에이스',
    nameEn: 'Ace of Wands',
    number: 1,
    keywords: ['새로운 시작', '창의력', '영감', '잠재력'],
    upright: '새로운 창조적 에너지가 피어오릅니다. 열정적인 시작, 영감 넘치는 아이디어가 찾아옵니다. 행동으로 옮길 때입니다.',
    reversed: '지연되는 시작, 창의적 막힘이 있을 수 있습니다. 방향을 재설정하고 에너지를 모으세요.',
    description: '구름에서 뻗어나온 손이 싹이 트는 완드를 들고 있습니다.',
    element: '불',
  },
  {
    id: 'two-of-wands',
    name: '완드 2',
    nameEn: 'Two of Wands',
    number: 2,
    keywords: ['계획', '결정', '미래', '진보'],
    upright: '장기적인 계획을 세울 때입니다. 세상이 당신 손 안에 있습니다. 대담한 결정을 내리세요.',
    reversed: '계획의 부재나 두려움으로 인한 정체가 있습니다. 안전지대를 벗어날 용기를 가지세요.',
    description: '성벽에 서서 지구본을 들고 먼 곳을 바라보는 인물.',
    element: '불',
  },
  {
    id: 'three-of-wands',
    name: '완드 3',
    nameEn: 'Three of Wands',
    number: 3,
    keywords: ['확장', '예견', '리더십', '기회'],
    upright: '노력의 결실이 보이기 시작합니다. 더 넓은 시야로 기회를 포착하세요. 확장의 시기입니다.',
    reversed: '계획의 장애물이나 예상치 못한 지연이 있습니다. 인내심을 가지세요.',
    description: '언덕에서 바다로 나가는 배들을 바라보는 상인.',
    element: '불',
  },
  {
    id: 'four-of-wands',
    name: '완드 4',
    nameEn: 'Four of Wands',
    number: 4,
    keywords: ['축하', '조화', '가정', '안정'],
    upright: '축하와 기쁨의 시간입니다. 가정의 평화, 중요한 이정표를 달성했습니다. 성과를 즐기세요.',
    reversed: '불안정한 기반이나 축하받지 못하는 성과가 있습니다. 내면의 평화를 찾으세요.',
    description: '꽃으로 장식된 네 개의 완드 아래 축제를 즐기는 사람들.',
    element: '불',
  },
  {
    id: 'five-of-wands',
    name: '완드 5',
    nameEn: 'Five of Wands',
    number: 5,
    keywords: ['갈등', '경쟁', '긴장', '다양성'],
    upright: '경쟁이나 갈등이 있지만 성장의 기회입니다. 건전한 경쟁은 발전을 가져옵니다.',
    reversed: '불필요한 갈등을 피하거나, 내면의 갈등을 해결할 때입니다.',
    description: '다섯 명의 젊은이들이 완드로 모의 전투를 벌입니다.',
    element: '불',
  },
  {
    id: 'six-of-wands',
    name: '완드 6',
    nameEn: 'Six of Wands',
    number: 6,
    keywords: ['승리', '인정', '성공', '자신감'],
    upright: '승리와 공개적 인정을 받습니다. 당신의 노력이 빛을 발합니다. 자신감을 가지세요.',
    reversed: '인정받지 못하거나 실패에 대한 두려움이 있습니다. 외부 평가에 너무 의존하지 마세요.',
    description: '월계관을 쓰고 말을 타고 행진하는 승리자.',
    element: '불',
  },
  {
    id: 'seven-of-wands',
    name: '완드 7',
    nameEn: 'Seven of Wands',
    number: 7,
    keywords: ['방어', '인내', '도전', '용기'],
    upright: '자신의 입장을 지켜야 할 때입니다. 도전에 맞서 싸우세요. 포기하지 마세요.',
    reversed: '압도당하는 느낌이나 포기하고 싶은 유혹이 있습니다. 전략적 후퇴도 방법입니다.',
    description: '높은 곳에서 아래의 도전자들을 막아서는 인물.',
    element: '불',
  },
  {
    id: 'eight-of-wands',
    name: '완드 8',
    nameEn: 'Eight of Wands',
    number: 8,
    keywords: ['속도', '행동', '움직임', '소식'],
    upright: '일이 빠르게 진행됩니다. 좋은 소식이 오고 있습니다. 지금 행동하세요.',
    reversed: '지연, 좌절 또는 너무 성급한 행동에 주의하세요. 때를 기다리세요.',
    description: '하늘을 가르며 날아가는 여덟 개의 완드.',
    element: '불',
  },
  {
    id: 'nine-of-wands',
    name: '완드 9',
    nameEn: 'Nine of Wands',
    number: 9,
    keywords: ['끈기', '회복력', '경계', '지속'],
    upright: '지쳤지만 거의 다 왔습니다. 마지막까지 포기하지 마세요. 당신은 충분히 강합니다.',
    reversed: '번아웃이나 피해의식에 주의하세요. 쉼이 필요할 수 있습니다.',
    description: '상처 입었지만 완드를 굳건히 지키는 전사.',
    element: '불',
  },
  {
    id: 'ten-of-wands',
    name: '완드 10',
    nameEn: 'Ten of Wands',
    number: 10,
    keywords: ['부담', '책임', '노력', '스트레스'],
    upright: '무거운 짐을 지고 있습니다. 책임감은 좋지만 과부하에 주의하세요. 도움을 요청해도 됩니다.',
    reversed: '짐을 내려놓거나 위임할 때입니다. 모든 것을 혼자 할 필요 없습니다.',
    description: '열 개의 완드를 힘겹게 나르는 인물.',
    element: '불',
  },
  {
    id: 'page-of-wands',
    name: '완드 시종',
    nameEn: 'Page of Wands',
    number: 11,
    keywords: ['탐험', '열정', '발견', '자유로운 영혼'],
    upright: '새로운 모험을 시작할 준비가 되었습니다. 호기심을 따라가세요. 창의적 영감이 넘칩니다.',
    reversed: '방향을 잃거나 아이디어가 현실화되지 않습니다. 집중력을 기르세요.',
    description: '완드를 들고 새로운 땅을 바라보는 젊은 메신저.',
    element: '불',
  },
  {
    id: 'knight-of-wands',
    name: '완드 기사',
    nameEn: 'Knight of Wands',
    number: 12,
    keywords: ['에너지', '열정', '모험', '충동'],
    upright: '열정적으로 목표를 향해 돌진하세요. 대담한 행동이 필요한 때입니다. 모험을 두려워하지 마세요.',
    reversed: '무모함이나 지속력 부족에 주의하세요. 열정을 지혜롭게 사용하세요.',
    description: '말을 타고 돌진하는 용감한 기사.',
    element: '불',
  },
  {
    id: 'queen-of-wands',
    name: '완드 여왕',
    nameEn: 'Queen of Wands',
    number: 13,
    keywords: ['자신감', '독립', '결단력', '카리스마'],
    upright: '자신감 있게 앞으로 나아가세요. 당신의 빛으로 주변을 밝히세요. 리더십을 발휘할 때입니다.',
    reversed: '질투나 자기 의심에 주의하세요. 진정한 자신감을 회복하세요.',
    description: '해바라기와 검은 고양이와 함께 왕좌에 앉은 당당한 여왕.',
    element: '불',
  },
  {
    id: 'king-of-wands',
    name: '완드 왕',
    nameEn: 'King of Wands',
    number: 14,
    keywords: ['리더십', '비전', '기업가 정신', '명예'],
    upright: '비전을 가지고 이끄세요. 당신의 창의적 리더십이 빛날 때입니다. 대담한 결정을 내리세요.',
    reversed: '독단적이거나 폭군적인 태도에 주의하세요. 겸손함이 필요합니다.',
    description: '도마뱀이 새겨진 왕좌에서 완드를 든 왕.',
    element: '불',
  },
]

// Minor Arcana - 컵 (Cups) - 물의 원소
export const cupsMeanings: TarotMeaning[] = [
  {
    id: 'ace-of-cups',
    name: '컵 에이스',
    nameEn: 'Ace of Cups',
    number: 1,
    keywords: ['새로운 감정', '사랑', '직관', '창의성'],
    upright: '새로운 사랑이나 깊은 감정적 경험이 시작됩니다. 마음을 열고 받아들이세요. 영적 충만함의 시기입니다.',
    reversed: '감정적 막힘이나 억압된 감정이 있습니다. 마음의 문을 여세요.',
    description: '구름에서 나온 손이 넘치는 성배를 들고 있습니다.',
    element: '물',
  },
  {
    id: 'two-of-cups',
    name: '컵 2',
    nameEn: 'Two of Cups',
    number: 2,
    keywords: ['파트너십', '연합', '사랑', '조화'],
    upright: '깊은 유대감과 파트너십이 형성됩니다. 상호 존중하는 관계, 사랑의 시작입니다.',
    reversed: '관계의 불균형이나 단절이 있습니다. 소통을 회복하세요.',
    description: '잔을 교환하며 서약하는 두 사람.',
    element: '물',
  },
  {
    id: 'three-of-cups',
    name: '컵 3',
    nameEn: 'Three of Cups',
    number: 3,
    keywords: ['축제', '우정', '커뮤니티', '축하'],
    upright: '친구들과 함께하는 기쁨의 시간입니다. 축하할 일이 있습니다. 사회적 유대감이 강해집니다.',
    reversed: '그룹 내 갈등이나 고립감이 있습니다. 관계를 회복하세요.',
    description: '잔을 들어 건배하는 세 명의 여인.',
    element: '물',
  },
  {
    id: 'four-of-cups',
    name: '컵 4',
    nameEn: 'Four of Cups',
    number: 4,
    keywords: ['명상', '무관심', '재평가', '불만족'],
    upright: '잠시 멈추고 내면을 돌아볼 때입니다. 눈앞의 기회를 놓치고 있을 수 있습니다.',
    reversed: '새로운 기회를 받아들이거나 무관심에서 벗어날 때입니다.',
    description: '나무 아래 앉아 제안된 잔을 무시하는 인물.',
    element: '물',
  },
  {
    id: 'five-of-cups',
    name: '컵 5',
    nameEn: 'Five of Cups',
    number: 5,
    keywords: ['상실', '슬픔', '후회', '실망'],
    upright: '상실의 슬픔을 느끼지만, 아직 남은 것이 있습니다. 잃은 것에만 집중하지 마세요.',
    reversed: '슬픔에서 벗어나 회복의 길로 들어섭니다. 용서와 치유의 시작입니다.',
    description: '쏟아진 세 잔을 바라보며 슬퍼하는 인물, 뒤에는 두 잔이 남아있습니다.',
    element: '물',
  },
  {
    id: 'six-of-cups',
    name: '컵 6',
    nameEn: 'Six of Cups',
    number: 6,
    keywords: ['향수', '추억', '순수함', '재회'],
    upright: '과거의 좋은 기억이나 옛 인연과의 재회가 있습니다. 순수했던 시절을 떠올려 보세요.',
    reversed: '과거에 집착하거나 앞으로 나아가지 못합니다. 현재에 집중하세요.',
    description: '어린 시절 정원에서 꽃이 담긴 잔을 주고받는 아이들.',
    element: '물',
  },
  {
    id: 'seven-of-cups',
    name: '컵 7',
    nameEn: 'Seven of Cups',
    number: 7,
    keywords: ['환상', '선택', '상상', '유혹'],
    upright: '많은 가능성이 있지만 모두 현실적이지는 않습니다. 환상과 현실을 구분하세요.',
    reversed: '명확한 선택을 하거나 환상에서 깨어날 때입니다.',
    description: '구름 속 일곱 개의 다양한 환상을 바라보는 인물.',
    element: '물',
  },
  {
    id: 'eight-of-cups',
    name: '컵 8',
    nameEn: 'Eight of Cups',
    number: 8,
    keywords: ['떠남', '실망', '탐구', '포기'],
    upright: '무언가를 뒤로하고 새로운 의미를 찾아 떠날 때입니다. 용감한 선택입니다.',
    reversed: '떠나기 두려워하거나 포기와 지속 사이에서 갈등합니다.',
    description: '달 아래 여덟 개의 잔을 두고 산을 향해 떠나는 인물.',
    element: '물',
  },
  {
    id: 'nine-of-cups',
    name: '컵 9',
    nameEn: 'Nine of Cups',
    number: 9,
    keywords: ['소원 성취', '만족', '행복', '감사'],
    upright: '소원이 이루어집니다. 감정적 만족과 행복의 시기입니다. 감사하는 마음을 가지세요.',
    reversed: '물질적 성공에도 공허함을 느끼거나 탐욕에 주의하세요.',
    description: '아홉 개의 잔 앞에서 만족스럽게 앉아있는 인물.',
    element: '물',
  },
  {
    id: 'ten-of-cups',
    name: '컵 10',
    nameEn: 'Ten of Cups',
    number: 10,
    keywords: ['행복', '가족', '조화', '완성'],
    upright: '완전한 정서적 행복과 가족의 조화입니다. 사랑으로 가득 찬 시기입니다.',
    reversed: '가정의 불화나 이상과 현실의 괴리가 있습니다. 소통으로 해결하세요.',
    description: '무지개 아래 행복한 가족의 모습.',
    element: '물',
  },
  {
    id: 'page-of-cups',
    name: '컵 시종',
    nameEn: 'Page of Cups',
    number: 11,
    keywords: ['창의성', '직관', '메시지', '감수성'],
    upright: '창의적 영감이나 감정적 메시지가 옵니다. 직관을 믿고 상상력을 발휘하세요.',
    reversed: '감정적 미성숙이나 창의적 막힘이 있습니다. 내면 아이를 치유하세요.',
    description: '잔에서 나온 물고기와 대화하는 젊은 메신저.',
    element: '물',
  },
  {
    id: 'knight-of-cups',
    name: '컵 기사',
    nameEn: 'Knight of Cups',
    number: 12,
    keywords: ['로맨스', '매력', '상상력', '제안'],
    upright: '로맨틱한 제안이나 창의적 기회가 찾아옵니다. 감정을 따라가세요.',
    reversed: '비현실적인 기대나 감정적 조종에 주의하세요.',
    description: '잔을 들고 천천히 다가오는 우아한 기사.',
    element: '물',
  },
  {
    id: 'queen-of-cups',
    name: '컵 여왕',
    nameEn: 'Queen of Cups',
    number: 13,
    keywords: ['연민', '직관', '돌봄', '감수성'],
    upright: '깊은 공감 능력과 직관을 발휘하세요. 자신과 타인을 돌보는 것이 중요합니다.',
    reversed: '감정에 휩쓸리거나 경계가 필요합니다. 자기 돌봄을 잊지 마세요.',
    description: '물가 왕좌에서 덮인 성배를 바라보는 공감적인 여왕.',
    element: '물',
  },
  {
    id: 'king-of-cups',
    name: '컵 왕',
    nameEn: 'King of Cups',
    number: 14,
    keywords: ['감정적 균형', '외교', '지혜', '차분함'],
    upright: '감정을 지혜롭게 다스리세요. 차분한 리더십과 외교적 해결이 필요합니다.',
    reversed: '감정적 불안정이나 조종에 주의하세요. 균형을 회복하세요.',
    description: '파도치는 바다 위 왕좌에서 차분하게 앉아있는 왕.',
    element: '물',
  },
]

// Minor Arcana - 검 (Swords) - 공기의 원소
export const swordsMeanings: TarotMeaning[] = [
  {
    id: 'ace-of-swords',
    name: '검 에이스',
    nameEn: 'Ace of Swords',
    number: 1,
    keywords: ['명확함', '진실', '돌파구', '정의'],
    upright: '진실이 밝혀지고 명확한 사고가 가능해집니다. 새로운 아이디어나 돌파구가 옵니다.',
    reversed: '혼란, 오해 또는 진실이 왜곡될 수 있습니다. 명확한 소통이 필요합니다.',
    description: '구름에서 뻗은 손이 왕관을 뚫는 검을 들고 있습니다.',
    element: '공기',
  },
  {
    id: 'two-of-swords',
    name: '검 2',
    nameEn: 'Two of Swords',
    number: 2,
    keywords: ['결정', '교착', '균형', '회피'],
    upright: '어려운 결정을 피하고 있습니다. 눈을 뜨고 상황을 직시해야 합니다.',
    reversed: '교착 상태가 풀리거나 억눌린 감정이 터져 나올 수 있습니다.',
    description: '눈을 가리고 두 검을 교차시킨 여인.',
    element: '공기',
  },
  {
    id: 'three-of-swords',
    name: '검 3',
    nameEn: 'Three of Swords',
    number: 3,
    keywords: ['슬픔', '심장', '배신', '이별'],
    upright: '마음의 상처나 슬픔을 겪고 있습니다. 아픔을 인정하고 치유하세요.',
    reversed: '치유가 시작되거나 고통에서 벗어나고 있습니다. 용서하세요.',
    description: '세 자루의 검이 꽂힌 심장.',
    element: '공기',
  },
  {
    id: 'four-of-swords',
    name: '검 4',
    nameEn: 'Four of Swords',
    number: 4,
    keywords: ['휴식', '회복', '명상', '고요'],
    upright: '휴식과 회복이 필요합니다. 잠시 멈추고 에너지를 재충전하세요.',
    reversed: '쉬지 못하거나 번아웃 직전입니다. 반드시 쉬어야 합니다.',
    description: '성당에서 휴식을 취하는 기사의 조각상.',
    element: '공기',
  },
  {
    id: 'five-of-swords',
    name: '검 5',
    nameEn: 'Five of Swords',
    number: 5,
    keywords: ['갈등', '패배', '배신', '승리의 대가'],
    upright: '이기더라도 잃는 것이 있습니다. 싸울 가치가 있는지 생각하세요.',
    reversed: '갈등이 해결되거나 화해의 가능성이 있습니다. 자존심을 내려놓으세요.',
    description: '패자들의 검을 모으는 승자의 씁쓸한 미소.',
    element: '공기',
  },
  {
    id: 'six-of-swords',
    name: '검 6',
    nameEn: 'Six of Swords',
    number: 6,
    keywords: ['전환', '이동', '회복', '떠남'],
    upright: '어려운 상황에서 벗어나 더 나은 곳으로 이동합니다. 치유의 여정입니다.',
    reversed: '변화에 저항하거나 떠나지 못하고 있습니다. 놓아줄 용기를 가지세요.',
    description: '뱃사공이 여인과 아이를 잔잔한 물로 데려갑니다.',
    element: '공기',
  },
  {
    id: 'seven-of-swords',
    name: '검 7',
    nameEn: 'Seven of Swords',
    number: 7,
    keywords: ['속임수', '전략', '은밀함', '도피'],
    upright: '교활한 전략이 필요하거나 누군가의 속임수에 주의하세요.',
    reversed: '비밀이 드러나거나 양심의 가책을 느낍니다. 정직해지세요.',
    description: '다섯 자루의 검을 들고 몰래 빠져나가는 인물.',
    element: '공기',
  },
  {
    id: 'eight-of-swords',
    name: '검 8',
    nameEn: 'Eight of Swords',
    number: 8,
    keywords: ['속박', '제한', '피해자 의식', '무력감'],
    upright: '갇힌 느낌이지만 대부분 자기 생각의 감옥입니다. 눈가리개를 벗으세요.',
    reversed: '자기 제한에서 벗어나거나 새로운 관점을 얻습니다.',
    description: '검에 둘러싸여 묶인 채 눈이 가려진 여인.',
    element: '공기',
  },
  {
    id: 'nine-of-swords',
    name: '검 9',
    nameEn: 'Nine of Swords',
    number: 9,
    keywords: ['불안', '악몽', '걱정', '절망'],
    upright: '밤새 걱정하고 있습니다. 두려움이 실제보다 크게 느껴집니다. 도움을 구하세요.',
    reversed: '불안에서 벗어나거나 상황이 나아지고 있습니다. 희망을 가지세요.',
    description: '침대에서 깨어나 머리를 감싸며 괴로워하는 인물.',
    element: '공기',
  },
  {
    id: 'ten-of-swords',
    name: '검 10',
    nameEn: 'Ten of Swords',
    number: 10,
    keywords: ['끝', '배신', '최악', '새벽'],
    upright: '최악의 순간이지만, 바닥을 찍으면 올라갈 일만 남았습니다. 끝이자 새로운 시작입니다.',
    reversed: '회복이 시작되거나 상황이 생각보다 나쁘지 않습니다.',
    description: '열 자루의 검이 등에 꽂힌 채 누워있는 인물, 동이 트고 있습니다.',
    element: '공기',
  },
  {
    id: 'page-of-swords',
    name: '검 시종',
    nameEn: 'Page of Swords',
    number: 11,
    keywords: ['호기심', '경계', '새 아이디어', '소통'],
    upright: '새로운 아이디어나 소식이 옵니다. 호기심을 가지고 배우세요. 말조심하세요.',
    reversed: '험담이나 미성숙한 의사소통에 주의하세요.',
    description: '바람 부는 언덕에서 검을 들고 주위를 살피는 젊은 메신저.',
    element: '공기',
  },
  {
    id: 'knight-of-swords',
    name: '검 기사',
    nameEn: 'Knight of Swords',
    number: 12,
    keywords: ['행동', '야망', '충동', '용감함'],
    upright: '빠르고 결단력 있게 행동하세요. 목표를 향해 돌진할 때입니다.',
    reversed: '성급함이나 무모한 행동에 주의하세요. 생각 후 행동하세요.',
    description: '돌풍 속에서 말을 달리며 돌진하는 기사.',
    element: '공기',
  },
  {
    id: 'queen-of-swords',
    name: '검 여왕',
    nameEn: 'Queen of Swords',
    number: 13,
    keywords: ['명료함', '독립', '직관', '경계'],
    upright: '감정에 휘둘리지 않고 명확하게 판단하세요. 경험에서 나온 지혜입니다.',
    reversed: '냉정함이 지나치거나 쓴 경험에 갇혀 있습니다. 마음을 열어보세요.',
    description: '구름 속 왕좌에서 검을 든 냉철한 여왕.',
    element: '공기',
  },
  {
    id: 'king-of-swords',
    name: '검 왕',
    nameEn: 'King of Swords',
    number: 14,
    keywords: ['지성', '권위', '진실', '윤리'],
    upright: '논리와 지성으로 판단하세요. 진실과 정의를 추구하는 리더십이 필요합니다.',
    reversed: '권력 남용이나 잔인한 논리에 주의하세요. 마음도 함께 써야 합니다.',
    description: '왕좌에서 하늘을 향해 검을 든 엄격한 왕.',
    element: '공기',
  },
]

// Minor Arcana - 펜타클 (Pentacles) - 땅의 원소
export const pentaclesMeanings: TarotMeaning[] = [
  {
    id: 'ace-of-pentacles',
    name: '펜타클 에이스',
    nameEn: 'Ace of Pentacles',
    number: 1,
    keywords: ['새로운 기회', '번영', '물질적 시작', '잠재력'],
    upright: '물질적 새로운 시작입니다. 재정적 기회나 새로운 직업이 찾아옵니다.',
    reversed: '기회를 놓치거나 재정적 계획이 필요합니다. 기초를 다지세요.',
    description: '구름에서 뻗은 손이 황금 동전을 들고 있고, 아래에는 정원이 있습니다.',
    element: '땅',
  },
  {
    id: 'two-of-pentacles',
    name: '펜타클 2',
    nameEn: 'Two of Pentacles',
    number: 2,
    keywords: ['균형', '적응', '유연성', '우선순위'],
    upright: '여러 가지를 저글링하고 있습니다. 유연하게 균형을 잡으세요.',
    reversed: '압도당하거나 균형을 잃었습니다. 우선순위를 정하세요.',
    description: '두 개의 동전을 저글링하는 젊은이, 뒤에는 파도치는 배.',
    element: '땅',
  },
  {
    id: 'three-of-pentacles',
    name: '펜타클 3',
    nameEn: 'Three of Pentacles',
    number: 3,
    keywords: ['팀워크', '협력', '기술', '학습'],
    upright: '협력과 팀워크가 성공을 가져옵니다. 전문성을 인정받는 시기입니다.',
    reversed: '팀 내 갈등이나 인정받지 못하는 느낌이 있습니다. 소통하세요.',
    description: '성당에서 설계도를 논의하는 장인과 건축가들.',
    element: '땅',
  },
  {
    id: 'four-of-pentacles',
    name: '펜타클 4',
    nameEn: 'Four of Pentacles',
    number: 4,
    keywords: ['안정', '보안', '소유욕', '집착'],
    upright: '재정적 안정이 있지만 지나친 집착은 금물입니다. 적절히 나누세요.',
    reversed: '인색함에서 벗어나거나 재정적 불안정이 있습니다. 균형을 찾으세요.',
    description: '네 개의 동전을 꽉 움켜쥔 채 앉아있는 인물.',
    element: '땅',
  },
  {
    id: 'five-of-pentacles',
    name: '펜타클 5',
    nameEn: 'Five of Pentacles',
    number: 5,
    keywords: ['어려움', '고난', '배제', '회복'],
    upright: '재정적 어려움이나 소외감을 겪고 있습니다. 도움이 가까이에 있습니다.',
    reversed: '어려운 시기가 끝나가거나 도움을 받게 됩니다. 희망을 가지세요.',
    description: '눈 내리는 밤, 불 켜진 교회 앞을 지나는 두 거지.',
    element: '땅',
  },
  {
    id: 'six-of-pentacles',
    name: '펜타클 6',
    nameEn: 'Six of Pentacles',
    number: 6,
    keywords: ['관대함', '나눔', '받음', '균형'],
    upright: '베풀거나 받을 때입니다. 관대함이 순환을 만듭니다. 공정하게 나누세요.',
    reversed: '한쪽으로 기울어진 관계나 조건부 관대함에 주의하세요.',
    description: '저울을 들고 가난한 이들에게 동전을 나눠주는 부자.',
    element: '땅',
  },
  {
    id: 'seven-of-pentacles',
    name: '펜타클 7',
    nameEn: 'Seven of Pentacles',
    number: 7,
    keywords: ['인내', '평가', '보상', '장기 투자'],
    upright: '노력의 결과를 기다리는 시기입니다. 조급해하지 말고 인내하세요.',
    reversed: '조급함이나 노력에 비해 부족한 결과에 좌절합니다. 방향을 점검하세요.',
    description: '자신이 가꾼 포도나무를 바라보는 농부.',
    element: '땅',
  },
  {
    id: 'eight-of-pentacles',
    name: '펜타클 8',
    nameEn: 'Eight of Pentacles',
    number: 8,
    keywords: ['장인정신', '기술', '근면', '완성'],
    upright: '기술을 갈고닦을 때입니다. 성실한 노력이 전문성을 만듭니다.',
    reversed: '지루함이나 완벽주의에 주의하세요. 또는 기술 향상이 필요합니다.',
    description: '동전을 정성껏 조각하는 장인.',
    element: '땅',
  },
  {
    id: 'nine-of-pentacles',
    name: '펜타클 9',
    nameEn: 'Nine of Pentacles',
    number: 9,
    keywords: ['풍요', '자립', '우아함', '성취'],
    upright: '자신의 노력으로 풍요를 이루었습니다. 성과를 즐기세요.',
    reversed: '물질에만 집중하거나 독립성이 부족합니다. 균형을 찾으세요.',
    description: '포도원에서 매를 손에 얹은 우아한 여인.',
    element: '땅',
  },
  {
    id: 'ten-of-pentacles',
    name: '펜타클 10',
    nameEn: 'Ten of Pentacles',
    number: 10,
    keywords: ['유산', '가족', '장기적 성공', '전통'],
    upright: '물질적 완성과 가족의 번영입니다. 다음 세대에 물려줄 유산을 생각하세요.',
    reversed: '가족 내 재정 갈등이나 전통에 대한 부담이 있습니다.',
    description: '부유한 가문의 세 세대가 함께하는 모습.',
    element: '땅',
  },
  {
    id: 'page-of-pentacles',
    name: '펜타클 시종',
    nameEn: 'Page of Pentacles',
    number: 11,
    keywords: ['기회', '학습', '새로운 기술', '실용적'],
    upright: '새로운 기술을 배우거나 실용적인 기회가 옵니다. 성실하게 시작하세요.',
    reversed: '기회를 놓치거나 비현실적인 계획에 주의하세요.',
    description: '초록 들판에서 동전을 연구하는 젊은 학생.',
    element: '땅',
  },
  {
    id: 'knight-of-pentacles',
    name: '펜타클 기사',
    nameEn: 'Knight of Pentacles',
    number: 12,
    keywords: ['책임', '신뢰', '끈기', '보수적'],
    upright: '느리지만 확실하게 나아갑니다. 책임감 있고 신뢰할 수 있는 행동입니다.',
    reversed: '지나친 완고함이나 정체에 주의하세요. 유연해지세요.',
    description: '들판에서 검은 말 위에 동전을 들고 묵묵히 서 있는 기사.',
    element: '땅',
  },
  {
    id: 'queen-of-pentacles',
    name: '펜타클 여왕',
    nameEn: 'Queen of Pentacles',
    number: 13,
    keywords: ['풍요', '돌봄', '실용적', '안정'],
    upright: '물질적 안정과 가정의 따뜻함을 제공합니다. 현실적인 돌봄이 필요합니다.',
    reversed: '일과 가정의 균형이 깨지거나 물질에 집착합니다.',
    description: '정원에서 동전을 품에 안고 앉아있는 자연 속의 여왕.',
    element: '땅',
  },
  {
    id: 'king-of-pentacles',
    name: '펜타클 왕',
    nameEn: 'King of Pentacles',
    number: 14,
    keywords: ['부', '사업', '안정', '리더십'],
    upright: '재정적 성공과 물질적 안정의 정점입니다. 지혜로운 경영이 필요합니다.',
    reversed: '탐욕이나 물질만능주의에 주의하세요. 가치관을 점검하세요.',
    description: '포도와 황소로 장식된 왕좌에서 동전을 든 부유한 왕.',
    element: '땅',
  },
]

// 전체 덱 (78장)
export const allTarotMeanings: TarotMeaning[] = [
  ...majorArcanaMeanings,
  ...wandsMeanings,
  ...cupsMeanings,
  ...swordsMeanings,
  ...pentaclesMeanings,
]

// 카드 ID로 해석 찾기
export function getMeaning(cardId: string): TarotMeaning | undefined {
  return allTarotMeanings.find(card => card.id === cardId)
}

// 랜덤 카드 뽑기 (정방향/역방향 포함)
export function drawRandomCards(count: number): { card: TarotMeaning; isReversed: boolean }[] {
  const shuffled = [...allTarotMeanings].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count).map(card => ({
    card,
    isReversed: Math.random() < 0.3, // 30% 확률로 역방향
  }))
}
